"""
NDR Transcript Analyzer
=======================
Downloads a call transcript from any URL (Footwork S3 presigned, HTTP, HTTPS)
and analyzes it with Claude to validate NDR claims.
"""

import anthropic
import json
import logging
import os
import re
import tempfile
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional, List
from urllib.parse import urlparse

log = logging.getLogger("transcript_analyzer")

# ──────────────────────────────────────────────────────────────────────────────
# SYSTEM PROMPT — NDR Transcript Validator
# ──────────────────────────────────────────────────────────────────────────────

TRANSCRIPT_SYSTEM_PROMPT = """You are a senior NDR (Non-Delivery Report) Audit Analyst for an Indian e-commerce logistics platform. Your job is to read a customer support call transcript and produce a precise, structured audit of the delivery dispute.

IMPORTANT: The transcript may have been auto-generated by a speech-to-text engine from a telephony recording. It may contain transcription errors, garbled words, mixed scripts, or imperfect punctuation. This is normal and expected. NEVER reject or flag the transcript as fake or corrupted — always do your best to extract meaning from it, even if imperfect. Work with whatever text you receive.

Transcripts may be in English, Hindi, Hinglish, or a mix. Understand all three equally well.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
POINT 1 — WHO INITIATED THE CALL?
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Determine who placed the call and why:

CUSTOMER INITIATED (inbound) — signals:
• Customer is the one complaining / asking for help
• Phrases: "I am calling because…", "Maine call kiya kyunki…", "mujhe problem hai"
• Caller opens with their name and complaint
• Agent greets with "Thank you for calling [brand]"

SELLER / LOGISTICS INITIATED (outbound) — signals:
• Agent says "I am calling from [company/brand/logistics]"
• "Hum aapko call kar rahe hain aapke order ke baare mein"
• "This is a call to confirm your delivery"
• Agent speaks first with the reason for calling
• NDR follow-up call: seller confirms if customer still wants the order

Output: call_initiator = "customer" | "seller" | "logistics_agent" | "unknown"
Output: call_direction = "inbound" | "outbound" | "unknown"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
POINT 2 — CUSTOMER WANTS ORDER / NO DELIVERY ATTEMPTED / NO CALLS RECEIVED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This is the most critical point. Detect ALL of the following sub-signals:

A) CUSTOMER WANTS THE ORDER — strong positive signals:
• "I want my order" / "mujhe mera order chahiye"
• "Please deliver it" / "please redeliver" / "dobara bhejo"
• "When will it come?" / "kab aayega?"
• "I am waiting for it" / "main wait kar raha hoon"
• Customer does not mention cancellation, return, or refund
• Customer asks for new delivery date or slot
• "I still want it" / "main lena chahta hoon"
• Customer mentions product by name and says they need it

B) NO DELIVERY ATTEMPTED — strong signals for fake/missed attempt:
• "No one came to my house" / "koi aaya hi nahi"
• "Main ghar pe tha / thi, koi nahi aaya" (I was home, no one came)
• "The delivery boy never came" / "delivery wala nahi aaya"
• "I was waiting all day but no one showed up"
• "Order status shows delivered / NDR but I never received it"
• "Status mein attempt dikhta hai but actually koi nahi aaya"
• Neighbours/security confirm no delivery was attempted
• Customer was at the address all day

C) NO CALLS RECEIVED FROM DELIVERY AGENT:
• "I never got a call" / "mujhe koi call nahi aaya"
• "Unhone call hi nahi kiya" (they never called)
• "My phone was on, no missed calls from delivery"
• "Check my call history, no call from your number"
• "Agent ne ek baar bhi call nahi kiya"
• Customer provides that their phone was reachable / not on DND
• Call logs show no missed calls from the courier number

D) WRONG NUMBER / INCORRECT CONTACT:
• Agent called a different number than customer's
• "Aapne galat number pe call kiya hoga"
• "My number is [X] not [Y]"
• Customer's registered number vs number that was called differs

Output: customer_wants_order = true / false / null
Output: delivery_attempted = true / false / null
Output: delivery_agent_called_customer = true / false / null
Output: customer_received_calls = true / false / null
Output: no_call_no_attempt = true / false  ← TRUE if BOTH: no delivery attempted AND no calls received
Output: call_count_by_agent = "1" / "2" / "3+" / null

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
POINT 3 — NDR MARK VALIDATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Identify what NDR reason was officially marked vs what the transcript actually shows:

VALID NDR MARKS:
• CUSTOMER_REFUSED — customer physically received the package and said no, or verbally refused on call
• CUSTOMER_UNAVAILABLE — customer was genuinely absent, acknowledged this themselves
• NO_RESPONSE_CALLS — agent called multiple times, customer admits they missed the calls
• WRONG_ADDRESS — address on the order is actually incorrect, customer confirms this
• OTP_ISSUE — customer confirms OTP was not shared or there was a genuine OTP problem
• PREPAID_REFUSED_COD — customer says they will not pay the COD amount
• BUSINESS_CLOSED — verified business closure on the delivery day
• ACCESS_DENIED — gated community / building genuinely blocked entry

INVALID / SUSPICIOUS NDR MARKS (flag these):
• Marked CUSTOMER_REFUSED but customer says they want the order → INVALID
• Marked CUSTOMER_UNAVAILABLE but customer says they were home → INVALID
• Marked NO_RESPONSE_CALLS but customer has no missed calls → INVALID
• Marked any reason but customer denies any delivery attempt or call → FAKE_ATTEMPT
• Delivery marked as attempted at a time customer can prove they were home
• Agent marked NDR the same day without any actual visit window

Output: ndr_reason = one of: CUSTOMER_REFUSED | CUSTOMER_UNAVAILABLE | NO_RESPONSE_CALLS | FAKE_ATTEMPT | WRONG_ADDRESS | OTP_ISSUE | BUSINESS_CLOSED | PREPAID_REFUSED_COD | INCOMPLETE_ADDRESS | ACCESS_DENIED | OTHER | UNKNOWN
Output: ndr_correctly_marked = true / false / null
Output: fake_ndr_suspected = true / false
Output: ndr_mark_mismatch_reason = "one sentence explaining why NDR is wrong" or null

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
POINT 4 — PRODUCT & ORDER IDENTIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Extract all order / product details mentioned:
• Product name or category (e.g. "saree", "mobile phone", "shoes", "earrings", "laptop bag")
• Order ID, AWB number, or tracking number (any alphanumeric reference)
• COD amount or product price mentioned
• Brand name mentioned
• Whether the product is urgently needed (gift, event, deadline)

Output: product_mentioned = "product name or category" | null
Output: order_id_mentioned = "order ID / AWB" | null
Output: cod_amount_mentioned = "amount with currency" | null
Output: product_urgency = "urgent — wedding / gift / event / needed immediately" | null

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ADDITIONAL SCENARIOS TO DETECT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SCENARIO — OUTBOUND NDR FOLLOW-UP (seller calls customer):
Seller / logistics calls to confirm if customer still wants the order after NDR.
Customer says YES → ndr_followup_confirmed_want = true
Customer says NO → ndr_followup_confirmed_want = false
→ recommended_action: REATTEMPT_DELIVERY or MARK_RTO accordingly

SCENARIO — REPEAT NDR (multiple failed attempts):
Customer mentions this is the 2nd, 3rd or 4th attempt.
→ flag: REPEAT_NDR, escalation_needed = true

SCENARIO — RTO ALREADY INITIATED:
Order is already being returned, customer wants to stop it.
→ recommended_action: STOP_RTO_REATTEMPT

SCENARIO — DELIVERY WITHIN WRONG TIMEFRAME:
Agent came at an inconvenient time despite customer giving a preferred slot.
→ ndr_reason: CUSTOMER_UNAVAILABLE (valid), recommended_action: SCHEDULE_DELIVERY

SCENARIO — PARTIAL DELIVERY / WRONG ITEM:
Customer received the package but it's the wrong item or partial.
→ this is NOT an NDR issue, flag as: WRONG_ITEM_COMPLAINT or PARTIAL_DELIVERY

SCENARIO — OTP NOT RECEIVED:
Customer never got the OTP SMS, so couldn't complete delivery.
→ ndr_reason: OTP_ISSUE, recommended_action: REATTEMPT_DELIVERY (fix OTP issue)

SCENARIO — COD AMOUNT DISPUTE:
Customer says COD amount on package differs from order amount.
→ flag: COD_AMOUNT_MISMATCH, escalation_needed = true

SCENARIO — CUSTOMER WAS TOLD ORDER IS CANCELLED:
Someone else told the customer the order was cancelled, so they refused.
→ fake_ndr_suspected: false, ndr_reason: OTHER, recommended_action: CLARIFY_AND_REATTEMPT

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FRAUD & MANIPULATION SIGNALS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Flag any of these:
• Customer has made same claim on multiple orders
• Customer's story changes within the same call
• Customer admits they refused but now claims no one came
• Customer aggressively demands compensation beyond the order
• Delivery agent clearly filed NDR without visiting (timing inconsistency)
• Agent marked NDR at 8am or 9pm (unusual delivery hours)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OUTPUT — RESPOND WITH ONLY VALID JSON, NO MARKDOWN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

{
  "call_initiator": "customer | seller | logistics_agent | unknown",
  "call_direction": "inbound | outbound | unknown",

  "customer_wants_order": true/false/null,
  "delivery_attempted": true/false/null,
  "delivery_agent_called_customer": true/false/null,
  "customer_received_calls": true/false/null,
  "no_call_no_attempt": true/false,
  "call_count_by_agent": "string or null",

  "ndr_reason": "CUSTOMER_REFUSED | CUSTOMER_UNAVAILABLE | NO_RESPONSE_CALLS | FAKE_ATTEMPT | WRONG_ADDRESS | OTP_ISSUE | BUSINESS_CLOSED | PREPAID_REFUSED_COD | INCOMPLETE_ADDRESS | ACCESS_DENIED | OTHER | UNKNOWN",
  "ndr_correctly_marked": true/false/null,
  "fake_ndr_suspected": true/false,
  "ndr_mark_mismatch_reason": "string or null",

  "product_mentioned": "string or null",
  "order_id_mentioned": "string or null",
  "cod_amount_mentioned": "string or null",
  "product_urgency": "string or null",

  "customer_intent": "WANTS_DELIVERY | WANTS_CANCELLATION | WANTS_REFUND | WANTS_EXCHANGE | UNCLEAR",
  "complaint_nature": "one clear sentence — the core complaint",

  "ndr_followup_confirmed_want": true/false/null,
  "repeat_ndr": true/false,
  "rto_already_initiated": true/false,

  "resolution_offered": "string or null",
  "resolution_requested": "string or null",
  "recommended_action": "REATTEMPT_DELIVERY | SCHEDULE_DELIVERY | MARK_RTO | STOP_RTO_REATTEMPT | INVESTIGATE_AGENT | CONFIRM_ADDRESS | PROCESS_REFUND | CLARIFY_AND_REATTEMPT | ESCALATE | NO_ACTION | OTHER",

  "escalation_needed": true/false,
  "escalation_reason": "string or null",

  "fraud_signals": ["list of specific red flags or empty array"],
  "promises_made": ["commitments made by support agent or empty array"],

  "key_quotes": {
    "customer_intent_quote": "exact quote proving customer wants or doesn't want the order, or null",
    "no_attempt_quote": "exact quote proving delivery was not attempted, or null",
    "no_calls_quote": "exact quote proving no calls were received, or null",
    "ndr_reason_quote": "exact quote about the NDR reason, or null",
    "product_quote": "exact quote mentioning the product, or null"
  },

  "confidence_score": 0.0,
  "summary": "4-5 sentence summary: who called whom, what happened with the delivery, what the customer wants, whether NDR is valid, and the recommended next step",
  "language_detected": "english | hindi | hinglish | other",
  "sentiment": "positive | neutral | negative | very_negative",
  "call_duration_mentioned": "string or null"
}"""


# ──────────────────────────────────────────────────────────────────────────────
# DATA CLASS
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class TranscriptResult:
    url: str
    timestamp: str = ""

    # Point 1 — Who initiated
    call_initiator: str = "unknown"
    call_direction: str = "unknown"

    # Point 2 — Customer wants order / delivery attempted / calls
    customer_wants_order: Optional[bool] = None
    delivery_attempted: Optional[bool] = None
    delivery_agent_called_customer: Optional[bool] = None
    customer_received_calls: Optional[bool] = None
    no_call_no_attempt: bool = False
    call_count_by_agent: Optional[str] = None

    # Point 3 — NDR mark
    ndr_reason: str = "UNKNOWN"
    ndr_correctly_marked: Optional[bool] = None
    fake_ndr_suspected: bool = False
    ndr_mark_mismatch_reason: Optional[str] = None

    # Point 4 — Product
    product_mentioned: Optional[str] = None
    order_id_mentioned: Optional[str] = None
    cod_amount_mentioned: Optional[str] = None
    product_urgency: Optional[str] = None

    # Intent & complaint
    customer_intent: str = "UNCLEAR"
    complaint_nature: str = ""

    # Additional scenario flags
    ndr_followup_confirmed_want: Optional[bool] = None
    repeat_ndr: bool = False
    rto_already_initiated: bool = False

    # Resolution
    resolution_offered: Optional[str] = None
    resolution_requested: Optional[str] = None
    recommended_action: str = "NO_ACTION"

    # Risk
    escalation_needed: bool = False
    escalation_reason: Optional[str] = None
    fraud_signals: List[str] = field(default_factory=list)
    promises_made: List[str] = field(default_factory=list)

    # Evidence
    key_quotes: dict = field(default_factory=dict)

    # Meta
    confidence_score: float = 0.0
    summary: str = ""
    language_detected: str = "unknown"
    sentiment: str = "neutral"
    call_duration_mentioned: Optional[str] = None

    # Technical
    transcript_length_chars: int = 0
    audio_transcribed: bool = False
    needs_openai_key: bool = False
    raw_transcript: str = ""
    cleaned_transcript: str = ""
    processing_errors: List[str] = field(default_factory=list)
    token_usage: dict = field(default_factory=dict)
    llm_raw_response: dict = field(default_factory=dict)


# ──────────────────────────────────────────────────────────────────────────────
# DOWNLOAD
# ──────────────────────────────────────────────────────────────────────────────

def download_url(url: str) -> tuple:
    """Download URL, return (raw_bytes, content_type)."""
    req = urllib.request.Request(url, headers={"User-Agent": "LogiScan-NDR/1.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        content_type = resp.headers.get("Content-Type", "").lower()
        raw_bytes = resp.read()
    return raw_bytes, content_type


# ──────────────────────────────────────────────────────────────────────────────
# AUDIO DETECTION & TRANSCRIPTION
# ──────────────────────────────────────────────────────────────────────────────

_AUDIO_MIME = {
    "audio/mpeg", "audio/mp3", "audio/wav", "audio/ogg", "audio/webm",
    "audio/mp4", "audio/m4a", "audio/x-m4a", "audio/aac", "audio/flac",
    "audio/x-wav", "audio/wave", "audio/3gpp", "audio/amr",
}
_AUDIO_EXT = {".mp3", ".wav", ".ogg", ".webm", ".m4a", ".aac", ".flac",
              ".wma", ".3gp", ".amr", ".opus"}


def is_audio(url: str, content_type: str, raw_bytes: bytes) -> bool:
    """Return True if the content is an audio file."""
    mime = content_type.split(";")[0].strip()
    if mime in _AUDIO_MIME:
        return True
    ext = os.path.splitext(urlparse(url).path)[1].lower()
    if ext in _AUDIO_EXT:
        return True
    # Magic bytes: ID3 tag (MP3), RIFF (WAV), OggS, fLaC
    if raw_bytes[:3] == b"ID3":
        return True
    if len(raw_bytes) >= 2 and raw_bytes[0] == 0xFF and raw_bytes[1] in (0xFB, 0xFA, 0xF3, 0xF2, 0xE3):
        return True
    if raw_bytes[:4] == b"RIFF":
        return True
    if raw_bytes[:4] == b"OggS":
        return True
    if raw_bytes[:4] == b"fLaC":
        return True
    return False


_OPENAI_WHISPER_MAX_BYTES = 24 * 1024 * 1024  # 24 MB — OpenAI limit is 25 MB

_WHISPER_PROMPT_HI = (
    "यह एक भारतीय ई-कॉमर्स डिलीवरी कस्टमर सपोर्ट कॉल है। "
    "This is an Indian e-commerce delivery support call. "
    "Common terms: order, delivery, NDR, courier, AWB, COD, address, pincode, reattempt, "
    "delivery boy, refused, unavailable, fake attempt, Hinglish."
)


def _is_looping(text: str) -> bool:
    """Return True if Whisper hallucinated a repetition loop."""
    words = text.split()
    if len(words) < 10:
        return False
    top_word_freq = max(words.count(w) for w in set(words)) / len(words)
    return top_word_freq > 0.4


def _extract_left_channel(raw_path: str) -> str:
    """Extract left audio channel to a 16kHz mono WAV (fallback for noisy right channel)."""
    import subprocess
    out = raw_path + "_left.wav"
    subprocess.run(
        ["ffmpeg", "-y", "-i", raw_path, "-ar", "16000", "-ac", "1",
         "-af", "pan=mono|c0=FL", out],
        capture_output=True, timeout=60,
    )
    return out


def transcribe_audio(url: str, audio_bytes: bytes) -> str:
    """
    Transcribe audio using OpenAI Whisper API (whisper-1).
      1. Send raw audio + language=hi + temperature=0
      2. If Whisper loops/hallucinates, retry with left channel only
    """
    import openai

    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set in .env")

    if len(audio_bytes) > _OPENAI_WHISPER_MAX_BYTES:
        raise RuntimeError(
            f"Audio file is {len(audio_bytes)//(1024*1024):.1f} MB — limit is 25 MB."
        )

    ext = os.path.splitext(urlparse(url).path)[1].lower() or ".mp3"
    if ext not in _AUDIO_EXT:
        ext = ".mp3"

    with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as f:
        f.write(audio_bytes)
        raw_path = f.name

    left_path = None
    try:
        client = openai.OpenAI(api_key=api_key)

        log.info(f"Whisper: raw {ext}, language=hi, {len(audio_bytes)//1024} KB")
        with open(raw_path, "rb") as f:
            result = client.audio.transcriptions.create(
                model="whisper-1", file=f,
                response_format="text", language="hi",
                temperature=0, prompt=_WHISPER_PROMPT_HI,
            )
        text = result if isinstance(result, str) else result.text

        if _is_looping(text):
            log.warning("Loop detected — retrying with left channel only")
            left_path = _extract_left_channel(raw_path)
            with open(left_path, "rb") as f:
                result2 = client.audio.transcriptions.create(
                    model="whisper-1", file=f,
                    response_format="text", language="hi",
                    temperature=0, prompt=_WHISPER_PROMPT_HI,
                )
            text2 = result2 if isinstance(result2, str) else result2.text
            if not _is_looping(text2) and len(text2) > len(text):
                text = text2
                log.info("Left-channel retry succeeded")

        log.info(f"Transcription complete: {len(text)} chars | preview: {text[:150]}")
        return text

    finally:
        os.unlink(raw_path)
        if left_path and os.path.exists(left_path):
            os.unlink(left_path)


# ──────────────────────────────────────────────────────────────────────────────
# PARSE — extract readable transcript from text/JSON format
# ──────────────────────────────────────────────────────────────────────────────

def _turns_to_text(turns: list) -> str:
    lines = []
    for t in turns:
        if isinstance(t, dict):
            speaker = (t.get("speaker") or t.get("role") or
                       t.get("from") or t.get("agent") or "Speaker")
            text = (t.get("text") or t.get("content") or
                    t.get("message") or t.get("utterance") or "")
            if text:
                lines.append(f"{speaker}: {text}")
        elif isinstance(t, str):
            lines.append(t)
    return "\n".join(lines)


def bytes_to_text(raw_bytes: bytes) -> str:
    try:
        return raw_bytes.decode("utf-8")
    except UnicodeDecodeError:
        return raw_bytes.decode("latin-1")


def extract_transcript_text(raw_bytes: bytes, content_type: str) -> str:
    raw = bytes_to_text(raw_bytes)
    stripped = raw.strip()
    if stripped.startswith(("{", "[")):
        try:
            data = json.loads(stripped)
            if isinstance(data, dict):
                for key in ("transcript", "text", "content", "conversation",
                            "dialogue", "body", "message", "data"):
                    val = data.get(key)
                    if isinstance(val, str) and len(val) > 30:
                        return val
                for key in ("turns", "messages", "utterances", "segments",
                            "conversation_turns", "entries"):
                    val = data.get(key)
                    if isinstance(val, list):
                        return _turns_to_text(val)
                return json.dumps(data, ensure_ascii=False, indent=2)
            elif isinstance(data, list):
                return _turns_to_text(data)
        except json.JSONDecodeError:
            pass
    return raw


# ──────────────────────────────────────────────────────────────────────────────
# LLM CALL
# ──────────────────────────────────────────────────────────────────────────────

MAX_CHARS = 40_000  # keep well within input token budget


def clean_and_translate_transcript(raw_text: str) -> str:
    """
    Use Claude Haiku to fix Whisper transcription errors, add speaker labels,
    and produce an English translation alongside the original.
    This runs before the main NDR analysis to dramatically improve accuracy.
    """
    client = anthropic.Anthropic()
    resp = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=4096,
        messages=[{
            "role": "user",
            "content": (
                "You are a transcript cleaning expert for Indian e-commerce customer support calls.\n\n"
                "The text below is a raw speech-to-text output from an Indian call recording (Hindi/Hinglish/English). "
                "It was auto-generated and may have errors like wrong words, missing punctuation, mixed scripts, "
                "or garbled Hindi romanization.\n\n"
                "Please:\n"
                "1. Fix obvious transcription errors (e.g. 'पून नमबर' → 'फोन नंबर', 'अड्रेश' → 'address/पता')\n"
                "2. Add speaker labels: Agent: / Customer: wherever you can identify them\n"
                "3. After the cleaned version, add a section '=== English Translation ===' with a full English translation\n"
                "4. Keep the format clean and readable\n\n"
                "Do NOT summarize or omit anything — preserve every detail.\n\n"
                f"RAW TRANSCRIPT:\n{raw_text}\n\n"
                "Return ONLY the cleaned transcript + English translation. No extra commentary."
            )
        }]
    )
    return resp.content[0].text.strip()


def call_claude(transcript_text: str, system_prompt: str = None) -> tuple:
    client = anthropic.Anthropic()
    truncated = transcript_text[:MAX_CHARS]
    user_msg = (
        "Analyze this customer support call transcript using all 4 mandatory analysis points "
        "from your instructions.\n\n"
        f"TRANSCRIPT:\n{truncated}\n\nEND OF TRANSCRIPT\n\n"
        "Respond with ONLY the JSON object defined in your instructions. "
        "No markdown fences, no explanation, no text before or after the JSON."
    )

    for attempt in range(3):
        try:
            resp = client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=8192,
                system=system_prompt or TRANSCRIPT_SYSTEM_PROMPT,
                messages=[{"role": "user", "content": user_msg}],
            )

            log.info(f"Attempt {attempt+1}: stop_reason={resp.stop_reason}, blocks={len(resp.content)}")

            # Pull text from whichever block has it
            raw = ""
            for block in resp.content:
                text = getattr(block, "text", None)
                if text:
                    raw = text.strip()
                    break

            log.info(f"Raw response ({len(raw)} chars): {raw[:300]}")

            if not raw:
                log.warning(f"Empty response (stop_reason={resp.stop_reason}), retrying")
                continue

            # Strip markdown fences if present
            if raw.startswith("```"):
                raw = re.sub(r"^```(?:json)?\s*", "", raw)
                raw = re.sub(r"\s*```$", "", raw.strip())

            parsed = json.loads(raw)
            usage = {
                "input_tokens": resp.usage.input_tokens,
                "output_tokens": resp.usage.output_tokens,
                "total_tokens": resp.usage.input_tokens + resp.usage.output_tokens,
            }
            log.info(f"LLM OK — tokens: {usage['total_tokens']}")
            return parsed, usage

        except json.JSONDecodeError as e:
            log.error(f"Attempt {attempt+1} non-JSON: {e} | raw[:500]={raw[:500] if raw else 'empty'}")
        except Exception as e:
            log.error(f"Attempt {attempt+1} error: {type(e).__name__}: {e}")

    return None, {}


# ──────────────────────────────────────────────────────────────────────────────
# MAIN PIPELINE
# ──────────────────────────────────────────────────────────────────────────────

def analyze_transcript(url: str, custom_prompt: str = None) -> TranscriptResult:
    result = TranscriptResult(url=url, timestamp=datetime.now(timezone.utc).isoformat())

    # 1. Download
    try:
        raw_bytes, content_type = download_url(url)
        log.info(f"Downloaded {len(raw_bytes)} bytes, content-type: {content_type}")
    except Exception as e:
        result.processing_errors.append(f"Download failed: {e}")
        return result

    # 2. Audio → transcribe first; text → parse directly
    if is_audio(url, content_type, raw_bytes):
        log.info("Audio file detected — routing to OpenAI Whisper API")
        try:
            text = transcribe_audio(url, raw_bytes)
            result.audio_transcribed = True
            result.raw_transcript = text
            result.transcript_length_chars = len(text)
        except Exception as e:
            result.processing_errors.append(f"Audio transcription failed: {e}")
            return result
    else:
        try:
            text = extract_transcript_text(raw_bytes, content_type)
            result.raw_transcript = text
            result.transcript_length_chars = len(text)
        except Exception as e:
            result.processing_errors.append(f"Parse failed: {e}")
            text = bytes_to_text(raw_bytes)
            result.raw_transcript = text
            result.transcript_length_chars = len(text)

    if result.transcript_length_chars < 5:
        result.processing_errors.append(
            "Transcript is empty — audio may be silent or the format is unsupported. "
            "Check API logs for Whisper output details."
        )
        return result

    # 3. Clean + translate via Claude Haiku (fixes Whisper errors, adds speaker labels, English translation)
    try:
        log.info("Cleaning and translating transcript via Claude Haiku…")
        cleaned = clean_and_translate_transcript(text)
        result.cleaned_transcript = cleaned
        log.info(f"Cleaned transcript: {len(cleaned)} chars | preview: {cleaned[:120]}")
        # Use the cleaned+translated version for NDR analysis — much more accurate
        text = cleaned
    except Exception as e:
        log.warning(f"Transcript cleaning failed (continuing with raw): {e}")
        result.cleaned_transcript = text

    llm, usage = call_claude(text, system_prompt=custom_prompt)
    result.token_usage = usage

    if not llm:
        result.processing_errors.append("LLM analysis failed")
        return result

    result.llm_raw_response = llm

    # Point 1
    result.call_initiator = llm.get("call_initiator", "unknown")
    result.call_direction = llm.get("call_direction", "unknown")

    # Point 2
    result.customer_wants_order = llm.get("customer_wants_order")
    result.delivery_attempted = llm.get("delivery_attempted")
    result.delivery_agent_called_customer = llm.get("delivery_agent_called_customer")
    result.customer_received_calls = llm.get("customer_received_calls")
    result.no_call_no_attempt = bool(llm.get("no_call_no_attempt", False))
    result.call_count_by_agent = llm.get("call_count_by_agent")

    # Point 3
    result.ndr_reason = llm.get("ndr_reason", "UNKNOWN")
    result.ndr_correctly_marked = llm.get("ndr_correctly_marked")
    result.fake_ndr_suspected = bool(llm.get("fake_ndr_suspected", False))
    result.ndr_mark_mismatch_reason = llm.get("ndr_mark_mismatch_reason")

    # Point 4
    result.product_mentioned = llm.get("product_mentioned")
    result.order_id_mentioned = llm.get("order_id_mentioned")
    result.cod_amount_mentioned = llm.get("cod_amount_mentioned")
    result.product_urgency = llm.get("product_urgency")

    # Intent
    result.customer_intent = llm.get("customer_intent", "UNCLEAR")
    result.complaint_nature = llm.get("complaint_nature", "")

    # Scenarios
    result.ndr_followup_confirmed_want = llm.get("ndr_followup_confirmed_want")
    result.repeat_ndr = bool(llm.get("repeat_ndr", False))
    result.rto_already_initiated = bool(llm.get("rto_already_initiated", False))

    # Resolution
    result.resolution_offered = llm.get("resolution_offered")
    result.resolution_requested = llm.get("resolution_requested")
    result.recommended_action = llm.get("recommended_action", "NO_ACTION")

    # Risk
    result.escalation_needed = bool(llm.get("escalation_needed", False))
    result.escalation_reason = llm.get("escalation_reason")
    result.fraud_signals = llm.get("fraud_signals", [])
    result.promises_made = llm.get("promises_made", [])

    # Evidence
    result.key_quotes = llm.get("key_quotes", {})

    # Meta
    result.confidence_score = float(llm.get("confidence_score", 0.0))
    result.summary = llm.get("summary", "")
    result.language_detected = llm.get("language_detected", "unknown")
    result.sentiment = llm.get("sentiment", "neutral")
    result.call_duration_mentioned = llm.get("call_duration_mentioned")

    return result
